### ISSUE TITLE
Error : The Maps API plugin (amap_maps_api) plugin is missing

### ISSUE THREAD

**Issue by rheman** [nlybe/agora#2]
Hi,
Thanks a lot for this great plugin,
I just installed the latest release, and I enabled Geo Maps API,
But when I click on Map Options, I get the following error message.
`The Maps API plugin (amap_maps_api) plugin is missing.`
When I click on PayPal Options I also have the following error.
`Paypal API plugin (paypal_api) is missing`
Where can I download the paypal_api ?
Could you help me ?

Regards,

**Comment by nlybe** [comment]
The paypal_api is not available at the moment, it will become available in near future for Elgg 3.x.

If you are using Elgg 2.x, you can get the amap_maps_api plugin at https://github.com/nlybe/Elgg-MapsAPI.
If using the Elgg 3.x, the maps api plugin is not ready yet.

**Comment by rheman** [comment]
Thanks a lot. I am using elgg 3.x
